apiVersion: mysql.radondb.com/v1beta1
kind: Backup
metadata:
  name: backup-sample
spec:
  backupops:
    s3:
      secretName: sample-backup-secret
  clusterName: sample
  method: xtrabackup
  # schedule:
  #   cronExpression: "*/2 * * * *"
  #   type: s3

